name: Release Build

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Build client
        run: cargo build --release -p cli --bin client

      - name: Build server
        run: cargo build --release -p cli --bin server

      - name: Prepare release assets
        run: |
          mkdir -p release
          cp target/release/client release/client
          cp target/release/server release/server
          cd release
          tar czf ../rust-binaries-linux-amd64.tar.gz *

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rust-binaries-linux-amd64.tar.gz
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
